import re
import os
import string


ITERATION_NUMBER = 10

ORIGINAL_LENGTH = 250
SHORT_ID_MAX_LENGTH = 16
SHORT_ID_AUTOGENERATED_MAX_LENGTH = 6

SHORT_ID_CHARACTER_SET = string.ascii_letters + string.digits
SHORT_ID_ALLOWED_CHARACTERS = '[%s]' % re.escape(SHORT_ID_CHARACTER_SET)


class Config(object):
    SQLALCHEMY_DATABASE_URI = os.getenv(
        'DATABASE_URI', default='sqlite:///db.sqlite3'
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.getenv('SECRET_KEY')
